### ISSUE TITLE
请问是否可以提供一个安装教程

### ISSUE THREAD

**Issue by littleheary** [TideSec/WDScanner#1]
请问是否可以提供一个安装教程，包括如何和那几个扫描器联动起来的配置等等的。

**Comment by alexanderhawl** [comment]
这个安装过程没说明真搞不定

**Comment by TideSec** [comment]
已经重新完善了安装教程，因为这个平台是之前做的，写的比较粗略，没想到这么多人关注~~不好意思~~

**Comment by yangdingfu** [comment]
求教程啊，如果能在linux上部署就太完美了

**Comment by TideSec** [comment]
下个版本准备在linux上重写~
