### ISSUE TITLE
我的虚拟机黑了，之后就不动....

### ISSUE THREAD

**Issue by kay6666** [TideSec/WDScanner#10]

**Comment by TideSec** [comment]
我用的win7+vm15和win10+vm15都测试过，都没有什么问题的

**Comment by trLcg** [comment]
![image](https://user-images.githubusercontent.com/97499908/233022177-21653241-a9d1-42db-a9cd-d3f9e1bf5104.png)
或许要关闭3d加速？我打开是黑屏的，关了就好了。
