### ISSUE TITLE
建议部署到ubuntu就好啦

### ISSUE THREAD

**Issue by wooluo** [TideSec/WDScanner#11]
awvs linux版本 下载地址链接：https://pan.baidu.com/s/1QMv-ocrwfMA9AnF1wMshXg 提取码：wegh
然后环境建议部署成docker环境，这样就方便多啦
里面的绝对路径有好多，自己安装太痛苦了。

**Comment by TideSec** [comment]
恩恩 好的 下一版就用linux  之前没有linux版的wvs  所以只能用windows
