### ISSUE TITLE
下载了百度网盘的虚拟机，添加扫描任务，扫描管理中显示不了；另外信息收集也回显不了结果

### ISSUE THREAD

**Issue by Scor09** [TideSec/WDScanner#12]
下载了百度网盘的虚拟机，添加扫描任务，扫描管理中显示不了；另外信息收集也回显不了结果

**Comment by TideSec** [comment]
添加任务在“管理中心”中添加后扫描、信息搜集和爬虫都会显示，而在“扫描任务”里添加的只有单项扫描。
