### ISSUE TITLE
批量添加任务的问题

### ISSUE THREAD

**Issue by I1ch** [TideSec/WDScanner#15]
大佬请问下，批量添加的任务，是要等这个批量任务执行完后，扫描信息、站点爬虫、信息收集的内容才会在系统页面上显示出来吗？
<img width="617" alt="1" src="https://user-images.githubusercontent.com/19966363/58527140-22fd0c80-8204-11e9-9f46-fd2a24437e08.png">
<img width="617" alt="2" src="https://user-images.githubusercontent.com/19966363/58527143-2395a300-8204-11e9-98bd-5385c3f0c83c.png">

**Comment by TideSec** [comment]
你这个应该是后台的任务脚本没有启动，正常来说添加后扫描和信息搜集都会同步启动，爬虫会在扫描结束后开始爬虫任务。
