### ISSUE TITLE
请问可以对IP地址的主机扫描吗？

### ISSUE THREAD

**Issue by Julythinkpad** [TideSec/WDScanner#23]
请问可以对IP地址的主机扫描吗？我将IP加入项目，最终全是0的结果，是不支持对IP地址的扫描吗？
![image](https://user-images.githubusercontent.com/27802843/62682795-8d45e080-b9ef-11e9-83a4-77812e0bf424.png)

**Comment by TideSec** [comment]
目前只支持对web应用的扫描，你可以在前面加http，如果你扫的不是web应用，建议使用Nessus
