### ISSUE TITLE
VMware15启动系统，不具有对某个分区的写访问权限。完全允许后，进入无限重启

### ISSUE THREAD

**Issue by Mt-hs** [TideSec/WDScanner#33]

**Comment by TideSec** [comment]
我用的win7+vm15和win10+vm15都测试过，都没有什么问题的。

**Comment by Conwy2021** [comment]
我升级win10后 遇到了 虚拟机启动win7时 提示不具有对某个分区的写访问权限   全部同意后 会直接蓝屏或者win7 一直重启
