### ISSUE TITLE
集成环境中使用带后门版本的phpstudy

### ISSUE THREAD

**Issue by snappyJack** [TideSec/WDScanner#35]
使用全局代理时发现phpstudy有异常流量：

![微信图片_20191104165302](https://user-images.githubusercontent.com/16055573/68108722-94638880-ff23-11e9-9688-0443f83e32b8.png)

#### 使用时请及时删除php_xmlrpc.dll

**Comment by TideSec** [comment]
这个还是之前的phpstudy版本，应该也是存在后门的，谢谢指出。
