### ISSUE TITLE
百度网盘链接失效，以及可否做个docker镜像这样跨平台也可运行

### ISSUE THREAD

**Issue by peniridis** [TideSec/WDScanner#42]
百度网盘链接失效，以及可否做个docker镜像这样跨平台也可运行 = =

**Comment by TideSec** [comment]
链接已经更新~~不用docker主要是因为里面扫描用的wvs，当时还没有出linux版的wvs，所以只能用windows，而winodws是没有dokcer镜像的，所以。。。不过目前已经在做linux版的扫描器~~希望能尽快面世~~
