### ISSUE TITLE
导入了数据库也配置好了config.inc.php但是还是出问题

### ISSUE THREAD

**Issue by j4543519** [TideSec/WDScanner#43]
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\phpstudy_pro\WWW\wdscan\include\mysql.class.php:27 Stack trace: #0 C:\phpstudy_pro\WWW\wdscan\include\mysql.class.php(20): mysql->connect() #1 C:\phpstudy_pro\WWW\wdscan\include\config.inc.php(41): mysql->__construct('192.168.199.147', 'wdscan', '123456', 'wdscan', 'utf-8', 'utf-8', '') #2 C:\phpstudy_pro\WWW\wdscan\index.php(2): require('C:\\phpstudy_pro...') #3 {main} thrown in C:\phpstudy_pro\WWW\wdscan\include\mysql.class.php on line 27

**Comment by TideSec** [comment]
貌似你是路径配置有点问题，可以下载完整版的虚拟机试一下~
