### ISSUE TITLE
扫描插件问题

### ISSUE THREAD

**Issue by sevck** [TideSec/WDScanner#5]
除了AWVS的扫描外，作者应该还有一个专项检测（插件检测），看了下没有调用的地方，也没有这个插件的目录 作者是没有开源全部吗？

**Comment by TideSec** [comment]
额，不好意思，插件检测因为当时做的时候没集成进来，后来有了新平台tide也没再更新这个，所以插件功能的确缺失，我们目前也是用的pocsuite框架，想加的话只能自己完善了，倒不算复杂，可以再添加个python任务调用pocsuite就可以了~~
