### ISSUE TITLE
可以在linux下运行吗

### ISSUE THREAD

**Issue by Trrinity** [TideSec/WDScanner#6]
这个web网站我部署到Linux 上了。。但是我看到要安装wvs？

**Comment by grayguest** [comment]
可以安装在其他机器上面，会发http request到linux server上的taskscan.php

**Comment by TideSec** [comment]
因为扫描是用的wvs，所以扫描节点得用windows系统~~

**Comment by wooluo** [comment]
> 因为扫描是用的wvs，所以扫描节点得用windows系统~~

linux版本的awvs 链接：https://pan.baidu.com/s/1QMv-ocrwfMA9AnF1wMshXg 提取码：wegh
