### ISSUE TITLE
节点配置

### ISSUE THREAD

**Issue by Nazicc** [TideSec/WDScanner#8]
节点配置，看了下，只有IP和端口，不知道具体的意义是什么，还有awvs10.5默认安装了就可以调用么？python环境，是2.7的，相应的库可有列表，或者做一个re清单。

**Comment by blockchainsecure** [comment]
wvs 不是 应该使用 api调用吗？

**Comment by Nazicc** [comment]
看了下，好像是命令调用，已经能用了

**Comment by TideSec** [comment]
已经重新打包了环境，提供了详细的安装说明~。
